### ISSUE TITLE
Fails to build due to missing linux/lsmpp_namespace.h

### ISSUE THREAD

**Issue by Ayowel** [Orange-OpenSource/SNAPPY#1]
## Issue

When trying to build with make from a fresh clone on master, compilation fails with the following error:

```
kernel/nsproxy.c:26:10: fatal error: linux/lsmpp_namespace.h: No such file or directory
   26 | #include <linux/lsmpp_namespace.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

The file `kernel/lsmpp_namespace.c` is commited and appears to provide the implementation of functions that should be exposed by the missing `include/linux/lsmpp_namespace.h`, do you happen to have it stored somewhere or should I generate it/initialize it after reading `kernel/lsmpp_namespace.c` ?

## Environment:

Kali on windows subsystem linux

Commands detail:

```
sudo apt-get install -y make gcc flex bison bc
make tinyconfig
make
```

**Comment by emixam16** [comment]
Hi Ayowel!

I forgot to include some some files in the tree. I will fix this quickly.

Thank you for pointing this out

**Comment by emixam16** [comment]
The issue should be fixed now.

Thank you again for pointing out this error.

Don't forget to configure your kernel with the following options:

```
- CONFIG_SECURITY=y
- CONFIG_SECURITYFS=y
- CONFIG_BPF=y
- CONFIG_BPF_SYSCALL=y
- CONFIG_LSMPP_NS=y
- CONFIG_SECURITY_WRITABLE_HOOKS=y
- CONFIG_SECURITY_LSMPP=y
- CONFIG_SECURITY_LSMPP_ENFORCE=y
- CONFIG_SECURITY_LSM="lsmpp,<other_LSMs_to_enable>"
```
